development:
  adapter: async

test:
  adapter: async

production:
#  adapter: postgresql
  adapter: async
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  #channel_prefix: workout_production
